### ISSUE TITLE
CURLOPT_SSL_VERIFYSTATUS not available on Linux

### ISSUE THREAD

**Issue by geertberkers** [IBM-Swift/CCurl#21]
I want to enable OCSP Stapling, according to [CURL](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYSTATUS.html) I should set CURLOPT_SSL_VERIFYSTATUS.
In XCode the project is building. But on linux I'll get the following error: 

```
/root/project/.build-ubuntu/checkouts/Kitura-net/Sources/KituraNet/ClientRequest.swift:652:38: error: use of unresolved identifier 'CURLOPT_SSL_VERIFYSTATUS'
        curlHelperSetOptInt(handle!, CURLOPT_SSL_VERIFYSTATUS, 1)
                                     ^~~~~~~~~~~~~~~~~~~~~~~~
CCurl.CURLOPT_SSL_VERIFYHOST:1:12: note: did you mean 'CURLOPT_SSL_VERIFYHOST'?
public var CURLOPT_SSL_VERIFYHOST: CURLoption { get }
           ^
CCurl.CURLOPT_SSL_VERIFYPEER:1:12: note: did you mean 'CURLOPT_SSL_VERIFYPEER'?
public var CURLOPT_SSL_VERIFYPEER: CURLoption { get }

```

Here is my Kitura-Net Fork I used to implement this:
https://github.com/geertberkers/Kitura-net/blob/c99aabe49911b24dd3c22d403e25014051694912/Sources/KituraNet/ClientRequest.swift#L652

**Comment by djones6** [comment]
@geertberkers I tried compiling your code locally and it seems to work for me (Ubuntu 18.04).  The option you are using was introduced in curl 7.41.  Is it possible that you have an older version?

Ubuntu 14.04 shipped curl 7.35, which would be too old,  but 16.04 and 18.04 ship newer versions (7.47 and 7.58 respectively) so your code should compile.

FYI, we did add a feature in the past (unix sockets support) which requires a newer curl than is available in 14.04, which we did via a helper so that the code continues to compile on 14.04 (albeit the feature is not supported): https://github.com/IBM-Swift/CCurl/commit/ef7406e8a8e5a8c151840ac9b7d3f64f24441e22

**Comment by djones6** [comment]
For reference, this issue was caused by the Dockerfiles vended by the `kitura init` CLI being based on Ubuntu 14.04.  However, I'm happy to report that these have been updated, and are now based on the official Swift images (Ubuntu 18.04).
